version: '3'

services:
  homepage:
    image: createdbyloid/staticpage:latest
    ports:
      - "4100:80"
    labels:
      - "com.centurylinklabs.watchtower.scope=homepage"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --scope homepage
    labels:
      - "com.centurylinklabs.watchtower.scope=homepage"